apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:3c65fea477d441c00c0961aa2e8745fa7bf95292e9ee4902abe5c0c02eaee521
type: application
version: 2.11.2
